# CONFIGURACI\u00D3N GENERAL BASE
spring.application.name=GestionStock
server.port=8080

# Indica qu\u00E9 perfil se ejecutar\u00E1 por defecto si no especificas nada en la terminal.
# Al poner 'dev', por defecto usar\u00E1 la base de datos 'aemas_dev' (de pruebas).
spring.profiles.active= dev



# Swagger
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operations-sorter=method


#El resto es antiguo.**************************************************************************
#Separado en dev y prod

# Configuracion de la conexion a PostgreSQL
#spring.datasource.url=jdbc:postgresql://localhost:5432/aemas_db
#spring.datasource.username=postgres
#spring.datasource.password=CHANGEME

# Configuracion de JPA / Hibernate
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# IMPORTANTE: Como ya has creado las tablas a mano con SQuirreL SQL,
# le decimos a Hibernate que solo valide que coincidan, que no intente crear nada nuevo.
#spring.jpa.hibernate.ddl-auto=validate


#Asi Hibernate puede crear columnas o tablas de forma automatica
#spring.jpa.hibernate.ddl-auto=update

# Muestra en la consola de IntelliJ las consultas SQL reales que ejecuta Hibernate por detras
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true

