# CONFIGURACI\u00D3N DE DESARROLLO (PRUEBAS)
spring.datasource.url=jdbc:postgresql://localhost:5432/aemas_dev
spring.datasource.username=postgres
spring.datasource.password=GHANGEME

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# En desarrollo permitimos que Hibernate cree o modifique tablas autom\u00E1ticamente
spring.jpa.hibernate.ddl-auto=update

# Mostramos el SQL en consola para ver qu\u00E9 hace en las pruebas
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true